### ISSUE TITLE
Filteröinti queryparametrien avulla

### ISSUE THREAD

**Issue by Ajhaa** [TKOaly/events-microservice#1]
Fuksipassin käyttöön tarvitsee vain suht tuoreita tapahtumia, joten suurin osa 1400+ eventistä on turhia. Olisi siis kätevää, jos haettavaa dataa voisi filtteröidä queryparametrien avulla.
esim: `https://members.tko-aly.fi/api/events?fromdate=2018-06-01`

**Comment by MergHQ** [comment]
Implemented
